# Pandas Problem Set

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics

In [3]:
url = "https://raw.githubusercontent.com/BeaverWorksMedlytics2020/Data_Public/master/NotebookExampleData/Week1/diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

Read in csv above to a pandas dataframe

In [4]:
# your code here
data = pd.read_csv(url, names=names)

Print out the age and class of the 100th patient

In [7]:
# your code here
data.loc[99, "age":"class"]

age      31.0
class     1.0
Name: 99, dtype: float64

Write code to figure out how many people are classified as not having diabetes, class is 0

In [12]:
# your code here
data[data["class"] ==0]

     preg  plas  pres  skin  test  mass   pedi  age  class
1       1    85    66    29     0  26.6  0.351   31      0
3       1    89    66    23    94  28.1  0.167   21      0
5       5   116    74     0     0  25.6  0.201   30      0
7      10   115     0     0     0  35.3  0.134   29      0
10      4   110    92     0     0  37.6  0.191   30      0
12     10   139    80     0     0  27.1  1.441   57      0
18      1   103    30    38    83  43.3  0.183   33      0
20      3   126    88    41   235  39.3  0.704   27      0
21      8    99    84     0     0  35.4  0.388   50      0
27      1    97    66    15   140  23.2  0.487   22      0
28     13   145    82    19   110  22.2  0.245   57      0
29      5   117    92     0     0  34.1  0.337   38      0
30      5   109    75    26     0  36.0  0.546   60      0
32      3    88    58    11    54  24.8  0.267   22      0
33      6    92    92     0     0  19.9  0.188   28      0
34     10   122    78    31     0  27.6  0.512   45      0
35      4   103    60    33   192  24.0  0.966   33      0
36     11   138    76     0     0  33.2  0.420   35      0
40      3   180    64    25    70  34.0  0.271   26      0
41      7   133    84     0     0  40.2  0.696   37      0
42      7   106    92    18     0  22.7  0.235   48      0
44      7   159    64     0     0  27.4  0.294   40      0
46      1   146    56     0     0  29.7  0.564   29      0
47      2    71    70    27     0  28.0  0.586   22      0
49      7   105     0     0     0   0.0  0.305   24      0
50      1   103    80    11    82  19.4  0.491   22      0
51      1   101    50    15    36  24.2  0.526   26      0
52      5    88    66    21    23  24.4  0.342   30      0
54      7   150    66    42   342  34.7  0.718   42      0
55      1    73    50    10     0  23.0  0.248   21      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
720     4    83    86    19     0  29.3  0.317   34      0
721     1   114    66    36   200  38.1  0.289   21      0
723     5   117    86    30   105  39.1  0.251   42      0
724     1   111    94     0     0  32.8  0.265   45      0
725     4   112    78    40     0  39.4  0.236   38      0
726     1   116    78    29   180  36.1  0.496   25      0
727     0   141    84    26     0  32.4  0.433   22      0
728     2   175    88     0     0  22.9  0.326   22      0
729     2    92    52     0     0  30.1  0.141   22      0
733     2   106    56    27   165  29.0  0.426   22      0
734     2   105    75     0     0  23.3  0.560   53      0
735     4    95    60    32     0  35.4  0.284   28      0
736     0   126    86    27   120  27.4  0.515   21      0
737     8    65    72    23     0  32.0  0.600   42      0
738     2    99    60    17   160  36.6  0.453   21      0
741     3   102    44    20    94  30.8  0.400   26      0
742     1   109    58    18   116  28.5  0.219   22      0
744    13   153    88    37   140  40.6  1.174   39      0
745    12   100    84    33   105  30.0  0.488   46      0
747     1    81    74    41    57  46.3  1.096   32      0
751     1   121    78    39    74  39.0  0.261   28      0
752     3   108    62    24     0  26.0  0.223   25      0
756     7   137    90    41     0  32.0  0.391   39      0
758     1   106    76     0     0  37.5  0.197   26      0
760     2    88    58    26    16  28.4  0.766   22      0
762     9    89    62     0     0  22.5  0.142   33      0
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
767     1    93    70    31     0  30.4  0.315   23      0

[500 rows x 9 columns]

Write code to figure out how many people are classified as having diabetes, class is 1

In [15]:
# your code here
diabetes = data[data["class"] ==1]
diabetes.count()

preg     268
plas     268
pres     268
skin     268
test     268
mass     268
pedi     268
age      268
class    268
dtype: int64

What percent of people have diabetes in the study

In [20]:
# your code here
diabetes.count()/data.count()

preg     0.348958
plas     0.348958
pres     0.348958
skin     0.348958
test     0.348958
mass     0.348958
pedi     0.348958
age      0.348958
class    0.348958
dtype: float64

Print out the pressure and class (no other columns) for the first 5 people (hint: this was not shown in our tutorial google how to select multiple columns with loc)

Being able to effectively google is a very important coding tool ¯\\\_(ツ)_/¯

In [21]:
# your code here
data.loc[:, ("pres", "class")]

     pres  class
0      72      1
1      66      0
2      64      1
3      66      0
4      40      1
5      74      0
6      50      1
7       0      0
8      70      1
9      96      1
10     92      0
11     74      1
12     80      0
13     60      1
14     72      1
15      0      1
16     84      1
17     74      1
18     30      0
19     70      1
20     88      0
21     84      0
22     90      1
23     80      1
24     94      1
25     70      1
26     76      1
27     66      0
28     82      0
29     92      0
..    ...    ...
738    60      0
739    74      1
740    80      1
741    44      0
742    58      0
743    94      1
744    88      0
745    84      0
746    94      1
747    74      0
748    70      1
749    62      1
750    70      1
751    78      0
752    62      0
753    88      1
754    78      1
755    88      1
756    90      0
757    72      1
758    76      0
759    92      1
760    58      0
761    74      1
762    62      0
763    76      0
764    70      0
765    72      0
766    60      1
767    70      0

[768 rows x 2 columns]

Run the cell below, it will print out the correlation among the columns

In [22]:
data.corr()

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
pedi,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

What column has the highest correlation with class? Find the mean() value of that column

In [26]:
# your code here
mean = np.mean(data.loc[:, "plas"])
mean

120.89453125

Create a new dataframe with only people that are above the mean found above

In [28]:
# your code here
data[data["plas"]>mean]

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
2       8   183    64     0     0  23.3  0.672   32      1
4       0   137    40    35   168  43.1  2.288   33      1
8       2   197    70    45   543  30.5  0.158   53      1
9       8   125    96     0     0   0.0  0.232   54      1
11     10   168    74     0     0  38.0  0.537   34      1
12     10   139    80     0     0  27.1  1.441   57      0
13      1   189    60    23   846  30.1  0.398   59      1
14      5   166    72    19   175  25.8  0.587   51      1
20      3   126    88    41   235  39.3  0.704   27      0
22      7   196    90     0     0  39.8  0.451   41      1
24     11   143    94    33   146  36.6  0.254   51      1
25     10   125    70    26   115  31.1  0.205   41      1
26      7   147    76     0     0  39.4  0.257   43      1
28     13   145    82    19   110  22.2  0.245   57      0
31      3   158    76    36   245  31.6  0.851   28      1
34     10   122    78    31     0  27.6  0.512   45      0
36     11   138    76     0     0  33.2  0.420   35      0
40      3   180    64    25    70  34.0  0.271   26      0
41      7   133    84     0     0  40.2  0.696   37      0
43      9   171   110    24   240  45.4  0.721   54      1
44      7   159    64     0     0  27.4  0.294   40      0
45      0   180    66    39     0  42.0  1.893   25      1
46      1   146    56     0     0  29.7  0.564   29      0
53      8   176    90    34   300  33.7  0.467   58      1
54      7   150    66    42   342  34.7  0.718   42      0
56      7   187    68    39   304  37.7  0.254   41      1
58      0   146    82     0     0  40.5  1.781   44      0
61      8   133    72     0     0  32.9  0.270   39      1
63      2   141    58    34   128  25.4  0.699   24      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
708     9   164    78     0     0  32.8  0.148   45      1
710     3   158    64    13   387  31.2  0.295   24      0
711     5   126    78    27    22  29.6  0.439   40      0
712    10   129    62    36     0  41.2  0.441   38      1
713     0   134    58    20   291  26.4  0.352   21      0
715     7   187    50    33   392  33.9  0.826   34      1
716     3   173    78    39   185  33.8  0.970   31      1
722     1   149    68    29   127  29.3  0.349   42      1
727     0   141    84    26     0  32.4  0.433   22      0
728     2   175    88     0     0  22.9  0.326   22      0
730     3   130    78    23    79  28.4  0.323   34      1
732     2   174    88    37   120  44.5  0.646   24      1
736     0   126    86    27   120  27.4  0.515   21      0
743     9   140    94     0     0  32.7  0.734   45      1
744    13   153    88    37   140  40.6  1.174   39      0
746     1   147    94    41     0  49.3  0.358   27      1
748     3   187    70    22   200  36.4  0.408   36      1
749     6   162    62     0     0  24.3  0.178   50      1
750     4   136    70     0     0  31.2  1.182   22      1
751     1   121    78    39    74  39.0  0.261   28      0
753     0   181    88    44   510  43.3  0.222   26      1
754     8   154    78    32     0  32.4  0.443   45      1
755     1   128    88    39   110  36.5  1.057   37      1
756     7   137    90    41     0  32.0  0.391   39      0
757     0   123    72     0     0  36.3  0.258   52      1
759     6   190    92     0     0  35.5  0.278   66      1
761     9   170    74    31     0  44.0  0.403   43      1
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1

[349 rows x 9 columns]

Create a new dataframe that only includes people who are above the average value for each column in the dataset (except 'class'). In other words, find the average value for each column, and then find which users have values above all of these average column values

In [36]:
# write code here
mean_table = data.mean()
mean_table = mean_table[:-1]
mean_dict = mean_table.to_dict()
filtered = data[(data['preg'] > mean_dict.get("preg")) & (data['plas'] > mean_dict.get("plas")) & (data['pres'] > mean_dict.get("pres"))
               & (data['skin'] > mean_dict.get("skin")) & (data['test'] > mean_dict.get("test")) 
               & (data['mass'] > mean_dict.get("mass")) & (data['pedi'] > mean_dict.get("pedi"))
               & (data['age'] > mean_dict.get("age"))]
filtered

     preg  plas  pres  skin  test  mass   pedi  age  class
43      9   171   110    24   240  45.4  0.721   54      1
152     9   156    86    28   155  34.3  1.189   42      1
159    17   163    72    41   114  40.9  0.817   47      1
175     8   179    72    42   130  32.7  0.719   36      1
206     8   196    76    29   280  37.5  0.605   57      1
215    12   151    70    40   271  41.8  0.742   38      1
236     7   181    84    21   192  35.9  0.586   51      1
259    11   155    76    28   150  33.3  1.353   51      1
286     5   155    84    44   545  38.7  0.619   34      0
375    12   140    82    43   325  39.2  0.528   58      1
424     8   151    78    32   210  42.9  0.516   36      1
458    10   148    84    48   237  37.6  1.001   51      1
546     5   187    76    27   207  43.6  1.034   53      1
594     6   123    72    45   230  33.6  0.733   34      0
603     7   150    78    29   126  35.2  0.692   54      1
612     7   168    88    42   321  38.2  0.787   40      1
614    11   138    74    26   144  36.1  0.557   50      1
663     9   145    80    46   130  37.9  0.637   40      1
744    13   153    88    37   140  40.6  1.174   39      0

In [53]:
means = mean_dict
for i in names:
    if i!='class':
        means[i] = data[i].mean()
ok = np.ndarray((data.shape[0]), dtype=bool)
ok.fill(True)

for i in names:
    if i!='class':
        ok = ok & (data[i]>means[i])

data3 = data[ok]
data3

     preg  plas  pres  skin  test  mass   pedi  age  class
43      9   171   110    24   240  45.4  0.721   54      1
152     9   156    86    28   155  34.3  1.189   42      1
159    17   163    72    41   114  40.9  0.817   47      1
175     8   179    72    42   130  32.7  0.719   36      1
206     8   196    76    29   280  37.5  0.605   57      1
215    12   151    70    40   271  41.8  0.742   38      1
236     7   181    84    21   192  35.9  0.586   51      1
259    11   155    76    28   150  33.3  1.353   51      1
286     5   155    84    44   545  38.7  0.619   34      0
375    12   140    82    43   325  39.2  0.528   58      1
424     8   151    78    32   210  42.9  0.516   36      1
458    10   148    84    48   237  37.6  1.001   51      1
546     5   187    76    27   207  43.6  1.034   53      1
594     6   123    72    45   230  33.6  0.733   34      0
603     7   150    78    29   126  35.2  0.692   54      1
612     7   168    88    42   321  38.2  0.787   40      1
614    11   138    74    26   144  36.1  0.557   50      1
663     9   145    80    46   130  37.9  0.637   40      1
744    13   153    88    37   140  40.6  1.174   39      0

In [54]:
df[np.sum(df.iloc[:, :-1] > np.array(np.mean(df))[:-1], axis=1) == 8]

NameError: name 'df' is not defined

Ignoring the index (resetting the index to 0), sort the values based on "skin", "test", and "pedi" values in ascending order. Please write this in one line.

In [42]:
# write code here 
data.sort_values(by = ["skin", "test", "pedi"], ascending = True)

     preg  plas  pres  skin  test  mass   pedi  age  class
268     0   102    52     0     0  25.1  0.078   21      0
180     6    87    80     0     0  23.2  0.084   32      0
598     1   173    74     0     0  36.8  0.088   38      1
81      2    74     0     0     0   0.0  0.102   22      0
430     2    99     0     0     0  22.2  0.108   23      0
560     6   125    76     0     0  33.8  0.121   54      1
714     3   102    74     0     0  29.5  0.121   32      0
474     4   114    64     0     0  28.9  0.126   24      0
678     3   121    52     0     0  36.0  0.127   25      1
319     6   194    78     0     0  23.5  0.129   59      1
586     8   143    66     0     0  34.9  0.129   41      1
7      10   115     0     0     0  35.3  0.134   29      0
404     5   168    64     0     0  32.9  0.135   41      1
154     8   188    78     0     0  47.9  0.137   43      1
333    12   106    80     0     0  23.6  0.137   44      0
619     0   119     0     0     0  32.4  0.141   24      1
729     2    92    52     0     0  30.1  0.141   22      0
190     3   111    62     0     0  22.6  0.142   21      0
762     9    89    62     0     0  22.5  0.142   33      0
628     5   128    80     0     0  34.6  0.144   45      0
708     9   164    78     0     0  32.8  0.148   45      1
207     5   162   104     0     0  37.7  0.151   52      1
401     6   137    61     0     0  24.2  0.151   55      0
524     3   125    58     0     0  31.6  0.151   24      0
636     5   104    74     0     0  28.8  0.153   48      0
616     6   117    96     0     0  28.7  0.157   30      0
624     2   108    64     0     0  30.8  0.158   21      0
400     4    95    64     0     0  32.0  0.161   31      1
283     7   161    86     0     0  30.4  0.165   47      1
433     2   139    75     0     0  25.6  0.167   29      0
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
422     0   102    64    46    78  40.6  0.496   21      0
177     0   129   110    46   130  67.1  0.319   26      1
663     9   145    80    46   130  37.9  0.637   40      1
428     0   135    94    46   145  40.6  0.284   26      0
718     1   108    60    46   178  35.5  0.415   24      0
689     1   144    82    46   180  46.1  0.335   46      1
662     8   167   106    46   231  37.6  0.165   43      1
625     4    90    88    47    54  37.7  0.362   29      0
575     1   119    44    47    63  35.5  0.280   25      0
39      4   111    72    47   207  37.1  1.390   56      1
16      0   118    84    47   230  45.8  0.551   31      1
763    10   101    76    48   180  32.9  0.171   63      0
657     1   120    80    48   200  38.9  1.162   41      0
458    10   148    84    48   237  37.6  1.001   51      1
370     3   173    82    48   465  38.4  2.137   25      1
693     7   129    68    49   125  38.5  0.439   43      1
539     3   129    92    49   155  36.4  0.968   32      1
409     1   172    68    49   579  42.4  0.702   28      1
273     1    71    78    50    45  33.2  0.422   21      0
591     2   112    78    50   140  39.4  0.175   24      0
150     1   136    74    50   204  37.4  0.399   24      0
99      1   122    90    51   220  49.7  0.325   31      1
275     2   100    70    52    57  40.5  0.677   25      0
532     1    86    66    52    65  41.3  0.917   29      0
86     13   106    72    54     0  36.6  0.178   45      0
211     0   147    85    54     0  42.8  0.375   24      0
120     0   162    76    56   100  53.2  0.759   25      1
57      0   100    88    60   110  46.8  0.962   31      0
445     0   180    78    63    14  59.4  2.420   25      1
579     2   197    70    99     0  34.7  0.575   62      1

[768 rows x 9 columns]

Notice that there are some repeats in values (like in the age and the preg column).

Now Let's find the 4 largest values for "age" and "mass". Reference the pandas documentation (https://pandas.pydata.org/docs/) if you are stuck!

In [46]:
# write code here
data.nlargest(4, "age")

     preg  plas  pres  skin  test  mass   pedi  age  class
459     9   134    74    33    60  25.9  0.460   81      0
453     2   119     0     0     0  19.6  0.832   72      0
666     4   145    82    18     0  32.5  0.235   70      1
123     5   132    80     0     0  26.8  0.186   69      0

In [47]:
data.nlargest(4, "mass")

     preg  plas  pres  skin  test  mass   pedi  age  class
177     0   129   110    46   130  67.1  0.319   26      1
445     0   180    78    63    14  59.4  2.420   25      1
673     3   123   100    35   240  57.3  0.880   22      0
125     1    88    30    42    99  55.0  0.496   26      1

Now find the smallest 4 values for "plas" and "preg" in reverse order (largest to smallest). Please refer to the API documentation if you are stuck-- https://pandas.pydata.org/pandas-docs/stable/reference/index.html

In [49]:
#write code here
plas = data.sort_values(by = "plas", ascending = False)
plas.head(4)

     preg  plas  pres  skin  test  mass   pedi  age  class
661     1   199    76    43     0  42.9  1.394   22      1
561     0   198    66    32   274  41.3  0.502   28      1
228     4   197    70    39   744  36.7  2.329   31      0
8       2   197    70    45   543  30.5  0.158   53      1

In [50]:
preg = data.sort_values(by = "preg", ascending = False)
preg.head(4)

     preg  plas  pres  skin  test  mass   pedi  age  class
159    17   163    72    41   114  40.9  0.817   47      1
88     15   136    70    32   110  37.1  0.153   43      1
298    14   100    78    25   184  36.6  0.412   46      1
455    14   175    62    30     0  33.6  0.212   38      1